package com.metecyu.yusr.ws.model;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

import java.util.List;

/**
 * User generated by hbm2java
 */
public class WsUserList implements java.io.Serializable {
	public List<WsUser> userList; 
}
