package com.metecyu.yusr.model;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

/**
 * DeptRoleRel generated by hbm2java
 */
public class DeptRoleRel implements java.io.Serializable {

	private String id;
	private Dept dept;
	private User user;
	private String roleid;
	private Integer orderno;

	public DeptRoleRel() {
	}

	public DeptRoleRel(Dept dept, User user, String roleid, Integer orderno) {
		this.dept = dept;
		this.user = user;
		this.roleid = roleid;
		this.orderno = orderno;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

}
