package com.metecyu.yusr.model;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

/**
 * Rolerel generated by hbm2java
 */
public class Rolerel implements java.io.Serializable {

	private String id;
	private Role role;
	private User user;
	private Integer orderno;

	public Rolerel() {
	}

	public Rolerel(String id) {
		this.id = id;
	}

	public Rolerel(String id, Role role, User user, Integer orderno) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.orderno = orderno;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

}
