package com.metecyu.yusr.model;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

/**
 * UserDeptRel generated by hbm2java
 */
public class UserDeptRel implements java.io.Serializable {

	private String id;
	private Dept dept;
	private User user;
	private Integer orderno;
	private String ismain;

	public UserDeptRel() {
	}

	public UserDeptRel(Dept dept, User user, Integer orderno, String ismain) {
		this.dept = dept;
		this.user = user;
		this.orderno = orderno;
		this.ismain = ismain;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	public String getIsmain() {
		return this.ismain;
	}

	public void setIsmain(String ismain) {
		this.ismain = ismain;
	}

}
