package com.metecyu.yusr.model;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String id;
	private String loginid;
	private String username;
	private String iseffect;
	private String password;
	private Date birthday;
	private String mobile;
	private String fjh;
	private String fphone;
	private String workstate;
	private String orgtype;
	private String sfzid;
	private String duty;
	private String dutydetails;
	private Set deptRoleRels = new HashSet(0);
	private Set rolerels = new HashSet(0);
	private Set userDeptRels = new HashSet(0);

	public User() {
	}

	public User(String loginid, String username, String iseffect,
			String password, Date birthday, String mobile, String fjh,
			String fphone, String workstate, String orgtype, String sfzid,
			String duty, String dutydetails, Set deptRoleRels, Set rolerels,
			Set userDeptRels) {
		this.loginid = loginid;
		this.username = username;
		this.iseffect = iseffect;
		this.password = password;
		this.birthday = birthday;
		this.mobile = mobile;
		this.fjh = fjh;
		this.fphone = fphone;
		this.workstate = workstate;
		this.orgtype = orgtype;
		this.sfzid = sfzid;
		this.duty = duty;
		this.dutydetails = dutydetails;
		this.deptRoleRels = deptRoleRels;
		this.rolerels = rolerels;
		this.userDeptRels = userDeptRels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLoginid() {
		return this.loginid;
	}

	public void setLoginid(String loginid) {
		this.loginid = loginid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getIseffect() {
		return this.iseffect;
	}

	public void setIseffect(String iseffect) {
		this.iseffect = iseffect;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFjh() {
		return this.fjh;
	}

	public void setFjh(String fjh) {
		this.fjh = fjh;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getWorkstate() {
		return this.workstate;
	}

	public void setWorkstate(String workstate) {
		this.workstate = workstate;
	}

	public String getOrgtype() {
		return this.orgtype;
	}

	public void setOrgtype(String orgtype) {
		this.orgtype = orgtype;
	}

	public String getSfzid() {
		return this.sfzid;
	}

	public void setSfzid(String sfzid) {
		this.sfzid = sfzid;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getDutydetails() {
		return this.dutydetails;
	}

	public void setDutydetails(String dutydetails) {
		this.dutydetails = dutydetails;
	}

	public Set getDeptRoleRels() {
		return this.deptRoleRels;
	}

	public void setDeptRoleRels(Set deptRoleRels) {
		this.deptRoleRels = deptRoleRels;
	}

	public Set getRolerels() {
		return this.rolerels;
	}

	public void setRolerels(Set rolerels) {
		this.rolerels = rolerels;
	}

	public Set getUserDeptRels() {
		return this.userDeptRels;
	}

	public void setUserDeptRels(Set userDeptRels) {
		this.userDeptRels = userDeptRels;
	}

}
