package com.metecyu.yusr.bmodel;

// Generated 2014-3-23 22:49:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.metecyu.yusr.model.User;

/**
 * User generated by hbm2java
 */
public class UserD extends User {

}
