
package testjws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "StudentWSService", targetNamespace = "http://ws.student.hqh.com", wsdlLocation = "http://localhost:8080/yusr/jaxws-spring?wsdl")
public class StudentWSService
    extends Service
{

    private final static URL STUDENTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTWSSERVICE_EXCEPTION;
    private final static QName STUDENTWSSERVICE_QNAME = new QName("http://ws.student.hqh.com", "StudentWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/yusr/jaxws-spring?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTWSSERVICE_WSDL_LOCATION = url;
        STUDENTWSSERVICE_EXCEPTION = e;
    }

    public StudentWSService() {
        super(__getWsdlLocation(), STUDENTWSSERVICE_QNAME);
    }

    public StudentWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IStudentWSService
     */
    @WebEndpoint(name = "studentServicePort")
    public IStudentWSService getStudentServicePort() {
        return super.getPort(new QName("http://ws.student.hqh.com", "studentServicePort"), IStudentWSService.class);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTWSSERVICE_EXCEPTION!= null) {
            throw STUDENTWSSERVICE_EXCEPTION;
        }
        return STUDENTWSSERVICE_WSDL_LOCATION;
    }

}
