
package testjws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "yusrWsSevice", targetNamespace = "http://ws.yusr.metecyu.com", wsdlLocation = "http://127.0.0.1:8080/yusr/jaxws-spring?wsdl")
public class YusrWsSevice
    extends Service
{

    private final static URL YUSRWSSEVICE_WSDL_LOCATION;
    private final static WebServiceException YUSRWSSEVICE_EXCEPTION;
    private final static QName YUSRWSSEVICE_QNAME = new QName("http://ws.yusr.metecyu.com", "yusrWsSevice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/yusr/jaxws-spring?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YUSRWSSEVICE_WSDL_LOCATION = url;
        YUSRWSSEVICE_EXCEPTION = e;
    }

    public YusrWsSevice() {
        super(__getWsdlLocation(), YUSRWSSEVICE_QNAME);
    }

    public YusrWsSevice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns YusrWsServiceItf
     */
    @WebEndpoint(name = "yusrWsSevicePort")
    public YusrWsServiceItf getYusrWsSevicePort() {
        return super.getPort(new QName("http://ws.yusr.metecyu.com", "yusrWsSevicePort"), YusrWsServiceItf.class);
    }

    private static URL __getWsdlLocation() {
        if (YUSRWSSEVICE_EXCEPTION!= null) {
            throw YUSRWSSEVICE_EXCEPTION;
        }
        return YUSRWSSEVICE_WSDL_LOCATION;
    }

}
